inputs_def:
  - handle: imageURL
    description: "%url-of-the-image-to-remove-background-from%"
    json_schema:
      type: string
    nullable: false

outputs_def:
  - handle: request_id
    description: "%the-request-id-returned-by-the-api-for-tracking-the-background-r%"
    json_schema:
      type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "%submit-background-removal%"
icon: ":carbon:image-search:"
description: "%submits-an-image-to-the-background-removal-api-and-returns-a-req%"
private: true
